# Generated by Django 4.2 on 2023-05-05 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_contest_time_alter_testcases_t_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
