# Generated by Django 4.2 on 2023-05-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_team_teamtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamTime',
            field=models.DateTimeField(),
        ),
    ]
