# Generated by Django 4.2.1 on 2023-05-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_team_teamtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
